package com.Application.entity;


import java.time.LocalDateTime;

import jakarta.persistence.*;

@Entity // Marks this class as a JPA entity
@Table(name = "notes") // Specifies the database table name for this entity
public class Notes {
    @Id // Marks this field as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the primary key is generated automatically by the database
    private Long noteId;

    @ManyToOne // Many-to-one relationship with the Patient entity
    @JoinColumn(name = "patient_id", referencedColumnName = "patientId", nullable = false) // Specifies the join column and its reference
    private Patient patient;

    @ManyToOne // Many-to-one relationship with the Doctor entity
    @JoinColumn(name = "doctor_id", referencedColumnName = "id", nullable = false) // Specifies the join column and its reference
    private Doctor doctor;

    @Column(name = "visited_date_time", nullable = false) // Indicates that this column cannot be null in the database
    private LocalDateTime visitedDateTime;

    @Column(columnDefinition = "TEXT") // Specifies that this column should be treated as a TEXT type in the database
    private String notes;

    // Constructors
    public Notes() {
        // Default constructor required by JPA
    }

    public Notes(Patient patient, Doctor doctor, LocalDateTime visitedDateTime, String notes) {
        this.patient = patient;
        this.doctor = doctor;
        this.visitedDateTime = visitedDateTime;
        this.notes = notes;
    }

    // Getters and Setters
    public Long getNoteId() {
        return noteId;
    }

    // noteId doesn't have a setter because it's auto-generated by the database

    public Patient getPatient() {
        return patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public Doctor getDoctor() {
        return doctor;
    }

    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

    public LocalDateTime getVisitedDateTime() {
        return visitedDateTime;
    }

    public void setVisitedDateTime(LocalDateTime visitedDateTime) {
        this.visitedDateTime = visitedDateTime;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    // Other properties, methods, and overrides can be added here...
}

