package com.Application.entity;

import jakarta.persistence.*;

@Entity // Marks this class as a JPA entity
@Table(name = "patients") // Specifies the database table name for this entity
public class Patient {
    @Id // Marks this field as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the primary key is generated automatically by the database
    private Long patientId;

    @Column(nullable = false) // Indicates that this column cannot be null in the database
    private String name;

    @Column( nullable = false) // Indicates that this column must be unique and cannot be null in the database
    private String contact;

    @Column(name = "last_visited_doctor_id") // Specifies the name of the column in the database for this field
    private Long lastVisitedDoctorId;

    // Constructors
    public Patient() {
        // Default constructor required by JPA
    }

    public Patient(String name, String contact) {
        this.name = name;
        this.contact = contact;
    }

    // Getters and Setters
    public Long getPatientId() {
        return patientId;
    }

    // patientId doesn't have a setter because it's auto-generated by the database

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public Long getLastVisitedDoctorId() {
        return lastVisitedDoctorId;
    }

    public void setLastVisitedDoctorId(Long lastVisitedDoctorId) {
        this.lastVisitedDoctorId = lastVisitedDoctorId;
    }

    // Other properties, methods, and overrides can be added here...
}
